import { Router } from "express";
import auth from "./modules/auth/auth.routes";
import products from "./modules/products/products.routes";
import { categoriesRouter, brandsRouter } from "./modules/catalog/catalog.routes";
import inventory from "./modules/inventory/inventory.routes";
import cart from "./modules/cart/cart.routes";
import wishlist from "./modules/wishlist/wishlist.routes";
import orders from "./modules/orders/orders.routes";
import reviews from "./modules/reviews/reviews.routes";
import coupons from "./modules/coupons/coupons.routes";
import account from "./modules/account/account.routes";
import users from "./modules/users/users.routes";
import employees from "./modules/employees/employees.routes";
import dashboard from "./modules/dashboard/dashboard.routes";
import cms from "./modules/cms/cms.routes";
import notifications from "./modules/notifications/notifications.routes";
import analytics from "./modules/analytics/analytics.routes";
import uploads from "./modules/uploads/uploads.routes";
import contact from "./modules/contact/contact.routes";

export const apiRouter = Router();
apiRouter.use("/auth", auth);
apiRouter.use("/products", products);
apiRouter.use("/categories", categoriesRouter);
apiRouter.use("/brands", brandsRouter);
apiRouter.use("/inventory", inventory);
apiRouter.use("/cart", cart);
apiRouter.use("/wishlist", wishlist);
apiRouter.use("/orders", orders);
apiRouter.use("/reviews", reviews);
apiRouter.use("/coupons", coupons);
apiRouter.use("/account", account);
apiRouter.use("/users", users);
apiRouter.use("/employees", employees);
apiRouter.use("/dashboard", dashboard);
apiRouter.use("/cms", cms);
apiRouter.use("/notifications", notifications);
apiRouter.use("/analytics", analytics);
apiRouter.use("/uploads", uploads);
apiRouter.use("/contact", contact);
